language: java
jdk:
  - oraclejdk8
 
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g tsd
 
script: ./gradlew test

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
